/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2cf50ee6-b075-4c83-9f39-66aa67193d20",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AF6iqtF0t",
    "aws_user_pools_web_client_id": "34ajvutek6u2r5272p63cc7kmh",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ydhbt7qohvedpccdhxgbokgnmu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r5xioorqsfc37dazmg3y4puqhi",
    "aws_user_files_s3_bucket": "fincountbucket01401-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
